#!/usr/bin/env python
"""Generate build metadata in a C++ header format and output it on stdout.
"""
import sys
import subprocess
import time


# All logs / warnings should be on stderr
def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)


r = subprocess.run("git describe --always --dirty", capture_output=True)

git_describe = r.stdout.strip().decode("utf-8")

output = f"""/*
This file was autogenerated by main/generate_build_metadata.py at: {time.strftime("%Y-%m-%d %H:%M:%S")}
*/

#ifndef _BUILD_METADATA_H
#define _BUILD_METADATA_H

constexpr char GIT_DESCRIBE[] = "{git_describe}";
constexpr int BUILD_TIME = {int(time.time())};

#endif // _BUILD_METADATA_H"""

print(output)
