name: Build firmware

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1.4
        target: esp32s3
        path: '.'

    - name: Upload bin
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}-${{ github.sha }}.bin
        path: build/${{ env.PROJECT_NAME }}.bin
