name: Build firmware

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1.4
        target: esp32s3
        path: '.'
        command: idf.py $(python ./generate_idf_flags_from_config_json.py release) build

    # this is the same way the CMake generates the tag.
    - name: Get git description
      run: echo "TAG=$(echo git describe --always --dirty)" >> $GITHUB_ENV

    - name: Upload bin
      uses: actions/upload-artifact@v4
      with:
        name: dynamite-sampler-firmware-release-${{ env.TAG }}.bin
        # This is hardcoded right now, but I'm not sure how to best not hardcode it
        path: build/release/dynamite-sampler-firmware.bin
