name: Build firmware

on:
  pull_request:
  workflow_dispatch:
  release:
    types: [published] # Triggers when you publish a new GitHub Release

# Required to allow the workflow to attach files to the release
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v6.1
        target: esp32s3
        path: '.'
        command: idf.py $(python ./generate_idf_flags_from_config_json.py release) build

    # this is the same way the main/generate_build_metadata.py generates the version.
    - name: Get git description
      run: echo "TAG=$(git describe --always --dirty --tags)" >> $GITHUB_ENV

    - name: Create firmware name
      run: echo "FIRMWARE_NAME=dynamite-sampler-firmware-release-${{ env.TAG }}.bin" >> $GITHUB_ENV

    # Rename the file on disk to include the TAG.
    - name: Prepare versioned binary
      run: cp build/release/dynamite-sampler-firmware.bin ${{ env.FIRMWARE_NAME }}

    # Keep the artifact upload for PRs and manual runs
    - name: Upload bin (Workflow Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.FIRMWARE_NAME }}
        path: ${{ env.FIRMWARE_NAME }}

    # Attach the binary to the GitHub Release (only runs on release events)
    - name: Upload bin (GitHub Release)
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v3
      with:
        files: ${{ env.FIRMWARE_NAME }}
